### ISSUE TITLE
[PM] Error when passing too many libraries to the deploy job

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris#1234]
There seems to be an upper limit to how many libraries can be specified in a deploy job, simply due to the length of the string it creates.
Removing any library from the invocation seen in the following snippet prevents the error.

```
Executing Job                                 AccountsManagerTest
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::status: Filename too long: "BaseErrors:62D9AE0976CAF9DB5ED7B05BD3BC49A6DE405F51  TypeUtilsAPI:1F08BA0C65873916558B07D3E991ABA72645CD8F  ArrayUtilsAPI:ACDEF044DD695955AED7E6F07BC6B020C10CE91C  Mappings:CAB5C8291F2C7A9A75C26E0223C4FC594F8687D0  OrganizationModel:5F4A6ACBE278C7DC026C7368D3BFFDFEE85D3EEF"
Error compiling contracts: Language error:
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::status: Filename too long: "BaseErrors:62D9AE0976CAF9DB5ED7B05BD3BC49A6DE405F51  TypeUtilsAPI:1F08BA0C65873916558B07D3E991ABA72645CD8F  ArrayUtilsAPI:ACDEF044DD695955AED7E6F07BC6B020C10CE91C  Mappings:CAB5C8291F2C7A9A75C26E0223C4FC594F8687D0  OrganizationModel:5F4A6ACBE278C7DC026C7368D3BFFDFEE85D3EEF"
```

Versions:
OSX version: 10.11.6
Eris CLI Version: 0.12.0
Docker:
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      darwin/amd64
Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
docker-machine version 0.9.0, build 15fd4c7

**Comment by j-h-scheufen** [comment]
@VoR0220 Please add "libraries" team label

**Comment by j-h-scheufen** [comment]
Additional details: It's been fine with 4-5 library references, but the error appears when using >= 6 libraries (as in the following example).
Note that it has not been tested if the error can be delayed when using shorter library names as keys, i.e. `M_API` instead of `MappingsAPI`.

```
- name: BlaTest
  job:
    deploy:
      contract: test/BlaTest.sol
      instance: all
      libraries: BaseErrors:$BaseErrors, TypeUtilsAPI:$TypeUtilsAPI, ArrayUtilsAPI:$ArrayUtilsAPI, Mappings:$Mappings, MappingsAPI:$MappingsImpl, OrganizationModel:$OrganizationModel
      wait: true
```
